inherit_from: .rubocop_todo.yml

inherit_gem:
  gc_ruboconfig: rubocop.yml

AllCops:
  TargetRubyVersion: 3.1

Style/CaseLikeIf:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Style/HashSyntax:
  Enabled: false
