version: 2.1

jobs:
  test:
    parameters:
      ruby-version:
        type: string
      rails-version:
        type: string

    docker:
      - image: cimg/ruby:<<parameters.ruby-version>>
        environment:
          - RAILS_VERSION=<<parameters.rails-version>>
    steps:
      - checkout

      - run: gem install bundler
      - run: bundle install

      - run: |
          bundle exec rspec --profile 10 \
                            --format RspecJunitFormatter \
                            --out /tmp/test-results/rspec.xml \
                            --format progress \
                            spec
      - store_test_results:
          path: /tmp/test-results

  rubocop:
    docker:
      - image: cimg/ruby:3.1
    steps:
      - checkout
      - run: gem install bundler -v 2.3.4
      - run: bundle install
      - run:
          name: Rubocop
          command: bundle exec rubocop --parallel --extra-details --display-style-guide

workflows:
  version: 2
  tests:
    jobs:
      - test:
          matrix:
            parameters:
              ruby-version: ["2.6", "2.7", "3.0", "3.1"]
              rails-version: ["5.2", "6.0", "6.1", "7.0"]
            exclude:
              - ruby-version: "3.0"
                rails-version: "5.2"
              - ruby-version: "3.1"
                rails-version: "5.2"
              - ruby-version: "2.6"
                rails-version: "7.0"
      - rubocop
