name: tests

on:
  push:
    branches:
      - "master"
  pull_request:

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ["3.2", "3.3", "3.4", "3.5"]
        rails-version: ["7.1", "7.2", "8.0"]
    runs-on: ubuntu-latest
    env:
      RAILS_VERSION: ${{ matrix.rails-version }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: "${{ matrix.ruby-version }}"
      - name: Run tests
        run: bundle exec rspec
      - name: Run rubocop
        run: bundle exec rubocop --parallel --extra-details --display-style-guide
